services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservicio-calidad-aire
    networks:
      - node-network
    ports:
      - "5000:5000"

networks:
  node-network:
    driver: bridge
